config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only:[:create, :new, :show]
  resource :session, only:[:new, :create, :destroy]

  resources :bands


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/band.rb
class Band < ApplicationRecord
    validates :name, presence:true
end

app/models/user.rb
class User < ApplicationRecord
    validates :session_token, :email, :password_digest, presence:true
    validates :password, length: {minimum: 6, allow_nil:true}

    attr_reader :password 

    after_initialize :ensure_session_token


    def self.find_by_credentials(email, password)
        user = User.find_by(email: email)
        return nil unless user && user.is_password?(password)
        user
    end
    
    def password=(password)
        @password = password
        self.password_digest = BCrypt::Password.create(password_digest)
    end

    def is_password?(password)
        BCrypt::Password.new(password_digest).is_password?(password)
    end 

    def reset_session_token!
        self.session_token ||= SecureRandom::urlsafe_base64
        self.save!
        self.session_token
    end

    private
    def ensure_session_token
        self.session_token ||= SecureRandom::urlsafe_base64
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base


    helper_method :current_user, :signed_in?

    private
    def current_user
        # debugger
        @current_user ||= User.find_by_session_token(session[:session_token])
    end

    def signed_in?
        !!current_user
    end

    def sign_in!(user)
        @current_user = user
        session[:session_token] = user.session_token
    end

    def sign_out
        current_user.reset_session_token!
        session[:session_token] = nil
        current_user = nil
    end
end

app/controllers/bands_controller.rb
class BandsController < ApplicationController
    def index
        Bands.all
    end

    def create
        @band = band.find_by(params[:id])
        if @band.save
            flash.now = 'ya saved a band bruh'
            render :show
        else
            flash[:errors] = @band.errors.full_messages
            redirect_to bands_url
        end
    end

    def new
        @band = Band.new
    end

    def edit
    end

    def show
    end
    
    def update
    end

    def destroy
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
        render :new
    end

    def create
        user = User.find_by_credentials(params[:user][:email], params[:user][:password])

        if user
            reditect_to user_url(user.id)
        else
            flash[:errors] = 'This aint right'
            render :new
        end
    end

    def destroy
        sign_out
        redirect_to new_user_url
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def new
        @user = User.new
        render :new
    end

    def create
        @user = User.new(user_params)
        # debugger
        if @user.save
            sign_in!(@user)
            redirect_to user_url(@user[:id])
        else
            flash.now[:errors] = @user.errors.full_messages
            render :new
        end

    end

    def show
        render :show
    end

    private
    def user_params
        params.require(:user).permit(:email, :password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bands/show.html.erb
<h2>all bands</h2>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ninenine</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <header> 
    <% if signed_in? %>
      <p><%= current_user.email %><%=  button_to 'LogOut', session_url, method: :delete%></p>
    <% end %>
    <%= yield %>
  </header>
  <body>
    <% if signed_in? %>
      
    <% end %>
  </body>
</html>

app/views/users/_form.html.erb
<% action = (user.persisted? ? user_url(user) : users_url) %>
<% method = (user.persisted? ? "patch" : "post") %>
<% message = (user.persisted? ? "Update user" : "Create user") %>

<form action="<%= action %>" method="post">
  <input
     name="_method"
     type="hidden"
     value="<%= method %>">
  <input
     name="authenticity_token"
     type="hidden"
     value="<%= form_authenticity_token %>">

  <label for="user_email">email</label>
  <input
     id="user_email"
     name="user[email]"
     type="text">
  <br>

  <label for="user_password">Password</label>
  <input
     id="user_password"
     name="user[password]"
     type="password">
  <br>

  <input type="submit" value="<%= message %>">
</form>

app/views/users/create.html.erb
<h1>is this it?</h1>

app/views/users/new.html.erb
<h1 class='page-header'>New User</h1>

<a class='button' href=<%= new_session_url %> >Go to sign-in</a>

<form class='form' action="<%= users_url %>" method="post">
  <input
    type="hidden"
    name="authenticity_token"
    value="<%= form_authenticity_token %>">

    <p>
        <label for='new-user-email'>Email
        <input id='new-user-email' type="text" name="user[email]">
        </label>
        <label for='new-user-password'>Password
        <input id='new-user-password' type="password" name="user[password]">
        </label>
    </p>
  <input type="submit" value="Submit">
</form>

app/views/users/show.html.erb
<h1 class='page-header'>User email</h1>
<p>
  Email: <%= current_user.email %>
</p>